### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by objectiser** [Maistra/maistra.github.io#26]
On the getting started page, there is a "Custom Installation" section - but there is no actual instructions for downloading and setting up the environment.

**Comment by JStickler** [comment]
@objectiser That's because https://github.com/Maistra/maistra.github.io/pull/14 hasn't been merged yet.  I keep bugging the team to merge the installation instructions.

**Comment by objectiser** [comment]
@JStickler Thanks Julie - sorry didn't check the open PRs :)
