### ISSUE TITLE
Improve formatting for monitoring and tracing on non-wide screens.

### ISSUE THREAD

**Issue by kaovilai** [Maistra/maistra.github.io#69]
See
https://maistra.io/docs/monitoring_and_tracing/
![image](https://user-images.githubusercontent.com/11228024/62323576-9a098800-b475-11e9-99f1-2929766dbb4e.png)
If I expand the window a little it becomes centered as expected but still with a thick border surrounding.
![image](https://user-images.githubusercontent.com/11228024/62323699-d9d06f80-b475-11e9-96e5-c9af419d128e.png)
As opposed to the pages immediately following which displayed just fine on non-wide screens
![image](https://user-images.githubusercontent.com/11228024/62323756-f7053e00-b475-11e9-838d-407d1c21c12c.png)

**Comment by dgn** [comment]
Cannot reproduce this, but this is probably an issue with our theme: https://github.com/matcornic/hugo-theme-learn

**Comment by brian-avery** [comment]
I'm also unable to reproduce this and Maistra.io has gone through a lot of changes this sprint, so this is likely fixed. The listing of articles is something that Maistra does differently than the theme we're based off of.

**Comment by kaovilai** [comment]
@brian-avery 
Reproduced just now
![image](https://user-images.githubusercontent.com/11228024/63898330-8abf2100-c9c6-11e9-9c73-17f4823bd610.png)

**Comment by kaovilai** [comment]
Eitherway the content background color should be consistent between pages.

**Comment by kaovilai** [comment]
Most pages looks like
![image](https://user-images.githubusercontent.com/11228024/63898470-1f298380-c9c7-11e9-81ae-8b2999957669.png)
But here is Examples and Monitoring and Tracing standing out with its unique background.
![image](https://user-images.githubusercontent.com/11228024/63898501-3a948e80-c9c7-11e9-802b-78665c2f44e7.png)
![image](https://user-images.githubusercontent.com/11228024/63898510-42543300-c9c7-11e9-97c5-63a5bc23d190.png)

**Comment by brian-avery** [comment]
Ah. Sorry, misunderstood. Was thinking you were referring to the content overflow in the initial screenshot. This is how it looks on the 1.0 preview. Still has the gray background, but now it's separate per issue rather than being a big block on the screen. 

![image](https://user-images.githubusercontent.com/8484260/63898820-81cf4f00-c9c8-11e9-98a4-761398897c2b.png)

While content looks like:
![image](https://user-images.githubusercontent.com/8484260/63898885-bba05580-c9c8-11e9-814a-c7e53c008b27.png)

**Comment by kaovilai** [comment]
Ok I think this is more acceptable. This issue can close once the preview made it to main page. (Or now if more convenient)

**Comment by brian-avery** [comment]
Thanks @kaovilai. Will close now and this change will be live on Maistra.io as soon as we switch to the new branch.
